// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-8b8670PqtKncs5qTWA08jh49vx9Lu8Y',
    appId: '1:1015878662447:web:63db9aadf3ae9bce2d09da',
    messagingSenderId: '1015878662447',
    projectId: 'ecm-delivery',
    authDomain: 'ecm-delivery.firebaseapp.com',
    storageBucket: 'ecm-delivery.firebasestorage.app',
    measurementId: 'G-YVD17J22TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLmH9jRrEVZpGhqBOmEMJg-pxnrXZPkes',
    appId: '1:1015878662447:android:aca166aea725a7182d09da',
    messagingSenderId: '1015878662447',
    projectId: 'ecm-delivery',
    storageBucket: 'ecm-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjhnGfDmZhK1IJ4z1iW89S6trlwJXE6Jk',
    appId: '1:1015878662447:ios:b1c28aa485541be12d09da',
    messagingSenderId: '1015878662447',
    projectId: 'ecm-delivery',
    storageBucket: 'ecm-delivery.firebasestorage.app',
    iosBundleId: 'com.example.eekcchutkimeinDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjhnGfDmZhK1IJ4z1iW89S6trlwJXE6Jk',
    appId: '1:1015878662447:ios:b1c28aa485541be12d09da',
    messagingSenderId: '1015878662447',
    projectId: 'ecm-delivery',
    storageBucket: 'ecm-delivery.firebasestorage.app',
    iosBundleId: 'com.example.eekcchutkimeinDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-8b8670PqtKncs5qTWA08jh49vx9Lu8Y',
    appId: '1:1015878662447:web:069796e60d99d1c62d09da',
    messagingSenderId: '1015878662447',
    projectId: 'ecm-delivery',
    authDomain: 'ecm-delivery.firebaseapp.com',
    storageBucket: 'ecm-delivery.firebasestorage.app',
    measurementId: 'G-V0MX3KX12E',
  );
}
